language: node_js
node_js:
  - "stable"
install:
  - yarn global add codecov
cache:
  directories:
    - node_modules
script:
  - yarn test
  - codecov
  - yarn run build
deploy:
  provider: pages
  local-dir: build
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  fqdn: rozig.me
  on:
    branch: master
